name: IPTV Update

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - run: pip install yt-dlp

      - run: mkdir -p output

      - run: python Global_Vision_list.py
      - run: python json_to_m3u.py

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "auto update" || echo "no changes"
          git push
